services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  mailhog:
    image: mailhog/mailhog
    platform: linux/x86_64
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  db-store:
